### ISSUE TITLE
Integration stopped working after update to v0.0.5

### ISSUE THREAD

**Issue by myakove** [0xAlon/dolphin#7]
After update, the all Dolphin entities are unavailable

```
Logger: homeassistant.components.sensor
Source: custom_components/dolphin/sensor.py:27
Integration: Sensor (documentation, issues)
First occurred: 12:21:49 PM (1 occurrences)
Last logged: 12:21:49 PM

Error while setting up dolphin platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/dolphin/sensor.py", line 27, in async_setup_entry
    for device in coordinator.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by synlink** [comment]
same here.. same error...
i really hope the author will fix it soon.. its critical !

**Comment by synlink** [comment]
deleting the integration and reinstalling it seems to fix the issue
thanks !

**Comment by myakove** [comment]
@synlink thxThanks

I think it's worth mentioning it in the change log @0xAlon
